[reapack]
name = Mariow Scripts
author = Mariow
url = https://github.com/Maginch/Reaper_Scripts-Mariow
description = Scripts REAPER développés par Mariow
donation = https://www.paypal.me/maginch

[filter]
; Inclure seulement les fichiers avec une extension script reconnue
include = *.lua;*.eel;*.py

; Exclure les fichiers non destinés à être indexés (facultatif)
exclude = *.md;*.txt;*.DS_Store;*/__archive__/*;*/deprecated/*;*.bak
