name: Generate ReaPack Index

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Generate index
        run: bundle exec reapack-index .

      - name: Validate index
        run: |
          if ! test -f index.xml; then
            echo "Error: index.xml not found!" && exit 1
          fi

      - name: Commit index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.xml
          git commit -m "Update index.xml [CI]" || echo "No changes to commit"
          git push
